### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by pumpadump** [neo4j-contrib/cypher-editor#9]
### Description
I'm trying to use cypher-codemirror in a react project. I copied the react CypherCodeMirror component and succesfully setup my site displaying the editor. Syntax highlighting is working but I don't seem to get the autocomplete to work. What configuration is necessary activate the autocomplete feature?

This is my component:
```
import * as React from 'react';
import { createCypherEditor } from 'cypher-codemirror';


//taken from :https://github.com/neo4j-contrib/cypher-editor/blob/master/cypher-codemirror/src/react/CypherCodeMirror.js

require('codemirror/lib/codemirror.css');
require('cypher-codemirror/src/css/completion.css')
require('cypher-codemirror/src/css/editor.css')
require('cypher-codemirror/src/css/syntax.css')

export default class CypherCodeMirror extends React.Component {

  constructor(props) {
    super(props);
    this.settings = props.settings || {};
    this.schema = props.schema || {};

    if (props.theme) {
      this.theme = props.theme;
      this.settings.theme = props.theme;
    }

    this.input = null;
    this.editorSupport = null;
    this.editor = null;
  }

  componentDidMount() {
    const { editor, editorSupport } = createCypherEditor(this.input, this.settings);
    this.editor = editor;
    this.editorSupport = editorSupport;
    this.editor.on('change', this.triggerAutocompletion.bind(this));
    this.editorSupport.setSchema(this.schema);
  }

  componentWillUpdate(nextProps) {
    if (nextProps.schema) {
      this.schema = nextProps.schema;
      this.editorSupport.setSchema(nextProps.schema);
    }

    if (nextProps.theme) {
      this.theme = nextProps.theme;
      this.settings.theme = nextProps.theme;
      this.editor.setOption('theme', this.theme);
    }
  }

  triggerAutocompletion(cm, changed) {
    this.props.queryCallback(cm.getValue())
    if (changed.text.length !== 1) {
      return;
    }

    const text = changed.text[0];
    const triggerAutocompletion = text === '.' ||
      text === ':' ||
      text === '[]' ||
      text === '()' ||
      text === '{}' ||
      text === '[' ||
      text === '(' ||
      text === '{' ||
      text === '$'
    if (triggerAutocompletion) {
      cm.execCommand('autocomplete');
    }
  }

  render() {
    const setInput = (input) => {
      this.input = input;
    };
    return <div className="Codemirror-Container" ref={setInput}/>;
  }
}
```

### Reproduce Steps
Setup a react project and use the above component to display a cypher editor field.

### Expected Behavior
I expected the autocompletion hints to popup when pressing one of the triggering buttons.

### Current Behavior
cm.execCommand('autocomplete'); Is triggered but nothing happens with the component.

### Your Environment

| software name  | version
| ---------------|----------
| OS               |  Windows 10
| Browser        |  Chrome 59
| node.js        | v6.10.2
| npm            | 3.10.10

**Comment by FylmTM** [comment]
Heya @pumpadump,

You are missing few things. Checkout out this file: https://github.com/neo4j-contrib/cypher-editor/blob/master/cypher-codemirror/dev/react/index.js

You need to add appropriate plugins from codemirror:

```
import 'codemirror/addon/lint/lint';
import 'codemirror/addon/hint/show-hint';
```

**Comment by pumpadump** [comment]
Hey @FylmTM 
thanks a ton, the autocomplete triggers now. 
I was also able to supply my own labels, property keys and relationship types via the schema object.
Do you know additional configuration options i can add to make the editor behave as close as possible to the full fledged cypher editor build into neo4j?

I've found alot of example configurations in https://github.com/neo4j-contrib/cypher-editor/blob/13dd609947ec45a49df74a9fde4ca21fb5e3c2fd/cypher-codemirror/dev/common.js

I will probably just try some of them.

Thanks again!
